#!/usr/bin/env node

// ---------------------------------------------------------------------------
// build-docs.js -- Reads .md files under src/docs/content/{locale}/ and writes
// one module per locale into each JavaScript build target's output, at
// dist/{node,esm}/docs/_generated/{locale}.{js,d.ts} -- the paths the package's
// "./docs/{locale}" export names.
//
// Each generated module exports:
//   tileContent: Record<string, string>   -- keyed by filename stem
//   conceptContent: Record<string, string> -- keyed by filename stem
// ---------------------------------------------------------------------------

const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const CONTENT_DIR = path.join(ROOT, "src", "docs", "content");
const DIST_DIR = path.join(ROOT, "dist");

/** Build target output directory names, and the module format each holds. */
const TARGETS = [
  { dir: "node", commonjs: true },
  { dir: "esm", commonjs: false },
];

/** Path within a target's output the generated modules are written to. */
const OUT_SUBDIR = path.join("docs", "_generated");

/** First line of every generated file. */
const BANNER = "// Auto-generated by scripts/build-docs.js -- DO NOT EDIT";

/** Read all .md files from a directory and return { stem: content } pairs. */
function readMdFiles(dir) {
  if (!fs.existsSync(dir)) return {};
  const entries = {};
  for (const file of fs.readdirSync(dir).sort()) {
    if (!file.endsWith(".md")) continue;
    const stem = file.slice(0, -3);
    entries[stem] = fs.readFileSync(path.join(dir, file), "utf-8");
  }
  return entries;
}

/** Escape a string for embedding in a JS template literal. */
function escapeTemplateLiteral(str) {
  return str.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

/**
 * Statement assigning `map` to the export named `name`, as an object literal
 * holding each entry's markdown in a template literal.
 *
 * @param {string} name - Name the module exports the map under
 * @param {Record<string, string>} map - Markdown keyed by filename stem
 * @param {boolean} commonjs - Emit a CommonJS assignment when true, an ES module export when false
 */
function exportStatement(name, map, commonjs) {
  const lines = [`${commonjs ? `exports.${name} = ` : `export const ${name} = `}{`];
  for (const [stem, content] of Object.entries(map)) {
    lines.push(`  "${stem}": \`${escapeTemplateLiteral(content)}\`,`);
  }
  lines.push("};");
  return lines.join("\n");
}

/** Source of one locale's module in the format `commonjs` selects. */
function generateLocaleModule(tilesMap, conceptsMap, commonjs) {
  const preamble = commonjs
    ? ['"use strict";', 'Object.defineProperty(exports, "__esModule", { value: true });', ""]
    : [];
  return [
    BANNER,
    "",
    ...preamble,
    exportStatement("tileContent", tilesMap, commonjs),
    "",
    exportStatement("conceptContent", conceptsMap, commonjs),
    "",
  ].join("\n");
}

/** Source of one locale's type declarations, the same for every target. */
function generateLocaleDeclaration() {
  return [
    BANNER,
    "",
    "export declare const tileContent: Record<string, string>;",
    "export declare const conceptContent: Record<string, string>;",
    "",
  ].join("\n");
}

/** Write `contents` to `file` when it differs from what is already there. */
function writeIfChanged(file, contents) {
  const current = fs.existsSync(file) ? fs.readFileSync(file, "utf-8") : undefined;
  if (current !== contents) fs.writeFileSync(file, contents, "utf-8");
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

if (!fs.existsSync(CONTENT_DIR)) {
  console.log("No docs content directory found, skipping docs generation.");
  process.exit(0);
}

const locales = fs
  .readdirSync(CONTENT_DIR, { withFileTypes: true })
  .filter((d) => d.isDirectory())
  .map((d) => d.name)
  .sort();

if (locales.length === 0) {
  console.log("No locale directories found under src/docs/content/, skipping.");
  process.exit(0);
}

const declaration = generateLocaleDeclaration();

for (const locale of locales) {
  const localeDir = path.join(CONTENT_DIR, locale);
  const tilesMap = readMdFiles(path.join(localeDir, "tiles"));
  const conceptsMap = readMdFiles(path.join(localeDir, "concepts"));

  for (const target of TARGETS) {
    const outDir = path.join(DIST_DIR, target.dir, OUT_SUBDIR);
    fs.mkdirSync(outDir, { recursive: true });
    writeIfChanged(path.join(outDir, `${locale}.js`), generateLocaleModule(tilesMap, conceptsMap, target.commonjs));
    writeIfChanged(path.join(outDir, `${locale}.d.ts`), declaration);
  }

  const tileCount = Object.keys(tilesMap).length;
  const conceptCount = Object.keys(conceptsMap).length;
  const targets = TARGETS.map((target) => `dist/${target.dir}`).join(", ");
  console.log(`docs: generated ${locale} (${tileCount} tiles, ${conceptCount} concepts) into ${targets}`);
}
