#!/usr/bin/env node

// ---------------------------------------------------------------------------
// build-docs.js -- Reads .md files under src/docs/content/{locale}/ and
// generates a TypeScript module per locale at src/docs/_generated/{locale}.ts.
//
// Each generated module exports:
//   tileContent: Record<string, string>   -- keyed by filename stem
//   conceptContent: Record<string, string> -- keyed by filename stem
//
// Run before tsc so the generated files are included in the build.
// ---------------------------------------------------------------------------

const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const CONTENT_DIR = path.join(ROOT, "src", "docs", "content");
const OUT_DIR = path.join(ROOT, "src", "docs", "_generated");

/** Read all .md files from a directory and return { stem: content } pairs. */
function readMdFiles(dir) {
  if (!fs.existsSync(dir)) return {};
  const entries = {};
  for (const file of fs.readdirSync(dir).sort()) {
    if (!file.endsWith(".md")) continue;
    const stem = file.slice(0, -3);
    entries[stem] = fs.readFileSync(path.join(dir, file), "utf-8");
  }
  return entries;
}

/** Escape a string for embedding in a JS template literal. */
function escapeTemplateLiteral(str) {
  return str.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

/** Generate a TypeScript module string for one locale. */
function generateLocaleModule(tilesMap, conceptsMap) {
  const lines = ["// Auto-generated by scripts/build-docs.js -- DO NOT EDIT", ""];

  // Tiles
  lines.push("export const tileContent: Record<string, string> = {");
  for (const [stem, content] of Object.entries(tilesMap)) {
    lines.push(`  "${stem}": \`${escapeTemplateLiteral(content)}\`,`);
  }
  lines.push("};");
  lines.push("");

  // Concepts
  lines.push("export const conceptContent: Record<string, string> = {");
  for (const [stem, content] of Object.entries(conceptsMap)) {
    lines.push(`  "${stem}": \`${escapeTemplateLiteral(content)}\`,`);
  }
  lines.push("};");
  lines.push("");

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

if (!fs.existsSync(CONTENT_DIR)) {
  console.log("No docs content directory found, skipping docs generation.");
  process.exit(0);
}

fs.mkdirSync(OUT_DIR, { recursive: true });

const locales = fs
  .readdirSync(CONTENT_DIR, { withFileTypes: true })
  .filter((d) => d.isDirectory())
  .map((d) => d.name)
  .sort();

if (locales.length === 0) {
  console.log("No locale directories found under src/docs/content/, skipping.");
  process.exit(0);
}

for (const locale of locales) {
  const localeDir = path.join(CONTENT_DIR, locale);
  const tilesMap = readMdFiles(path.join(localeDir, "tiles"));
  const conceptsMap = readMdFiles(path.join(localeDir, "concepts"));

  const tileCount = Object.keys(tilesMap).length;
  const conceptCount = Object.keys(conceptsMap).length;

  const moduleSource = generateLocaleModule(tilesMap, conceptsMap);
  const outFile = path.join(OUT_DIR, `${locale}.ts`);
  fs.writeFileSync(outFile, moduleSource, "utf-8");

  console.log(`docs: generated ${locale}.ts (${tileCount} tiles, ${conceptCount} concepts)`);
}
