*

!packages/bridge-client/package.json
!packages/bridge-client/tsconfig.json
!packages/bridge-client/src

!apps/vscode-bridge/package.json
!apps/vscode-bridge/tsconfig.json
!apps/vscode-bridge/tsconfig.base.json
!apps/vscode-bridge/src
