import type { FileContent } from "@wendoo-lang/app-host";
import { fileContentEquals, fileContentFromWire, fileContentText } from "@wendoo-lang/app-host";
import type { FolderCompilerFilesPayload } from "@wendoo-lang/bridge-protocol";
import { EXTENSIONS_TREE_PATH, INSTALLED_EXTENSIONS_METADATA_PATH } from "@wendoo-lang/bridge-protocol";

/** Project-relative path of the generated TypeScript project configuration. */
export const GENERATED_TSCONFIG_PATH = "tsconfig.json";

/** Project-relative path of the project's `.gitignore`. */
export const GITIGNORE_PATH = ".gitignore";

/** Marker comment line prefixed to the generated `tsconfig.json` on disk. */
export const GENERATED_TSCONFIG_MARKER =
  "// Generated by Wendoo. Regenerated on project open and on library changes; edits are overwritten.";

/** Marker comment line heading the `.gitignore` entries the writer appends. */
export const GITIGNORE_MARKER = "# Wendoo generated files";

/** The `.gitignore` entries covering the generated files. */
const GITIGNORE_ENTRIES = [`${EXTENSIONS_TREE_PATH}/`, GENERATED_TSCONFIG_PATH] as const;

/** File operations the affordance writer performs against the project folder. */
export interface AffordanceFileAccess {
  /** Read a file; undefined when it is missing or unreadable. */
  readFile(path: string): Promise<FileContent | undefined>;
  /** Write a file, creating missing parent directories. */
  writeFile(path: string, content: FileContent): Promise<void>;
  /** Delete a file; a no-op when it is missing. */
  deleteFile(path: string): Promise<void>;
  /** Recursively list the file paths under `directory`; empty when it does not exist. */
  listFilesUnder(directory: string): Promise<string[]>;
  /** Delete `directory` when it is empty; a no-op otherwise. */
  deleteDirectoryIfEmpty(path: string): Promise<void>;
}

/** Paths written and pruned by one {@link ProjectAffordanceWriter.apply}. */
export interface AffordanceApplyResult {
  /** Project-relative paths whose on-disk content this apply wrote. */
  writtenPaths: readonly string[];
  /** Project-relative paths this apply deleted. */
  deletedPaths: readonly string[];
}

/** The generated tsconfig's on-disk form: the marker comment ahead of the generated content. */
export function renderGeneratedTsconfig(content: string): string {
  return `${GENERATED_TSCONFIG_MARKER}\n${content}`;
}

/** True when a `.gitignore` line ignores `entry` (leading/trailing slashes disregarded). */
function gitignoreLineCovers(line: string, entry: string): boolean {
  const trimmed = line.trim();
  if (trimmed.length === 0 || trimmed.startsWith("#")) {
    return false;
  }
  const normalize = (value: string): string => value.replace(/^\/+/, "").replace(/\/+$/, "");
  return normalize(trimmed) === normalize(entry);
}

/**
 * The `.gitignore` text covering `entries` (defaulting to the generated file
 * entries): existing content is preserved byte-for-byte and any missing entries
 * are appended under a marker comment. Returns undefined when every entry is
 * already covered.
 */
export function updatedGitignoreContent(
  existing: string | undefined,
  entries: readonly string[] = GITIGNORE_ENTRIES
): string | undefined {
  const lines = existing === undefined ? [] : existing.split(/\r?\n/);
  const missing = entries.filter((entry) => !lines.some((line) => gitignoreLineCovers(line, entry)));
  if (missing.length === 0) {
    return undefined;
  }
  const block = `${GITIGNORE_MARKER}\n${missing.join("\n")}\n`;
  if (existing === undefined || existing.length === 0) {
    return block;
  }
  return existing.endsWith("\n") ? `${existing}${block}` : `${existing}\n${block}`;
}

/** The directory portion of `path`, or undefined for a root-level path. */
function parentDirectory(path: string): string | undefined {
  const index = path.lastIndexOf("/");
  return index > 0 ? path.slice(0, index) : undefined;
}

function isTreePath(path: string): boolean {
  return path === EXTENSIONS_TREE_PATH || path.startsWith(`${EXTENSIONS_TREE_PATH}/`);
}

/**
 * Materializes the app's compiler-controlled file set into the project
 * folder: the generated `tsconfig.json` (marker-prefixed), the
 * installed-extensions tree with its provenance record, and any ambient
 * declaration files, plus a `.gitignore` covering the generated entries.
 *
 * Each {@link apply} reconciles in place: unchanged files are left untouched,
 * files under the tree that left the set are deleted (with now-empty
 * directories pruned), and paths outside the tree written by an earlier apply
 * are deleted when they leave the set.
 */
export class ProjectAffordanceWriter {
  private readonly fileAccess: AffordanceFileAccess;
  /** Paths outside the installed-extensions tree owned by the writer. */
  private managedPaths = new Set<string>([GENERATED_TSCONFIG_PATH]);

  constructor(fileAccess: AffordanceFileAccess) {
    this.fileAccess = fileAccess;
  }

  /**
   * True for a path the writer owns on disk: the generated `tsconfig.json`,
   * anything under the installed-extensions tree, and any path the last
   * apply wrote outside it.
   */
  isAffordancePath(path: string): boolean {
    return path === GENERATED_TSCONFIG_PATH || isTreePath(path) || this.managedPaths.has(path);
  }

  /** Reconcile the project folder's generated files against `payload`. */
  async apply(payload: FolderCompilerFilesPayload): Promise<AffordanceApplyResult> {
    const expected = new Map<string, FileContent>();
    for (const [path, wire] of payload.files) {
      const content = fileContentFromWire(wire);
      expected.set(
        path,
        path === GENERATED_TSCONFIG_PATH ? renderGeneratedTsconfig(fileContentText(content) ?? "") : content
      );
    }
    if (Object.keys(payload.installedExtensions).length > 0) {
      expected.set(INSTALLED_EXTENSIONS_METADATA_PATH, JSON.stringify(payload.installedExtensions, null, 2));
    }

    const stale = new Set<string>(await this.fileAccess.listFilesUnder(EXTENSIONS_TREE_PATH));
    for (const path of this.managedPaths) {
      stale.add(path);
    }

    const writtenPaths: string[] = [];
    const deletedPaths: string[] = [];
    for (const [path, content] of expected) {
      stale.delete(path);
      const existing = await this.fileAccess.readFile(path);
      if (existing === undefined || !fileContentEquals(existing, content)) {
        await this.fileAccess.writeFile(path, content);
        writtenPaths.push(path);
      }
    }
    for (const path of stale) {
      await this.fileAccess.deleteFile(path);
      deletedPaths.push(path);
    }
    await this.pruneEmptyTreeDirectories(deletedPaths);
    this.managedPaths = new Set([GENERATED_TSCONFIG_PATH, ...[...expected.keys()].filter((path) => !isTreePath(path))]);

    const existingGitignore = await this.fileAccess.readFile(GITIGNORE_PATH);
    const gitignore = updatedGitignoreContent(
      existingGitignore === undefined ? undefined : fileContentText(existingGitignore)
    );
    if (gitignore !== undefined) {
      await this.fileAccess.writeFile(GITIGNORE_PATH, gitignore);
      writtenPaths.push(GITIGNORE_PATH);
    }
    return { writtenPaths, deletedPaths };
  }

  /** Delete tree directories emptied by the given deletions, deepest first. */
  private async pruneEmptyTreeDirectories(deletedPaths: readonly string[]): Promise<void> {
    const candidates = new Set<string>();
    for (const path of deletedPaths) {
      let directory = parentDirectory(path);
      while (directory !== undefined && isTreePath(directory)) {
        candidates.add(directory);
        directory = parentDirectory(directory);
      }
    }
    const deepestFirst = [...candidates].sort((a, b) => b.split("/").length - a.split("/").length);
    for (const directory of deepestFirst) {
      await this.fileAccess.deleteDirectoryIfEmpty(directory);
    }
  }
}
